### ISSUE TITLE
functions-framework-python does not work with python 3.13+

### ISSUE THREAD

**Issue by mrbuk** [GoogleCloudPlatform/functions-framework-python#350]
Running `functions-framework-python` with Python 3.13 leads to the following error:
```
% functions-framework-python --target check_http
Traceback (most recent call last):
  File "/Users/mbukowski/workspace/chronicle-export-data/.venv/bin/functions-framework-python", line 5, in <module>
    from functions_framework._cli import _cli
  File "/Users/mbukowski/workspace/chronicle-export-data/.venv/lib/python3.13/site-packages/functions_framework/__init__.py", line 37, in <module>
    from functions_framework import (
    ...<4 lines>...
    )
  File "/Users/mbukowski/workspace/chronicle-export-data/.venv/lib/python3.13/site-packages/functions_framework/_function_registry.py", line 19, in <module>
    from re import T
ImportError: cannot import name 'T' from 're' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py)
```
Trying to run `from re import T` directly in Python 3.13 leads to the same error
```
Python 3.13.0 (main, Oct 19 2024, 02:19:02) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from re import T
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from re import T
ImportError: cannot import name 'T' from 're' (/usr/local/lib/python3.13/re/__init__.py)
```

in comparison for 3.12 it works

```
Python 3.12.7 (main, Oct 19 2024, 03:00:35) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from re import T
>>>
```

Assumption is that this is due to the deprecation of `typing.re` in Python 3.13 as described in the GH Issue [Deprecate the typing.io and typing.re pseudo-modules #82472](https://github.com/python/cpython/issues/82472)

**Comment by nifflets** [comment]
Thanks for bringing this to our attention! This was also noticed by @glasnt in https://github.com/GoogleCloudPlatform/functions-framework-python/pull/349 which has now been merged. It should be fixed now in v3.8.2
